#!/usr/bin/env python3
"""tele -- run a command on a remote host, idempotently and immune to hangups.

Implements https://github.com/sjpb/tele/blob/main/README.md

Design in one paragraph
-----------------------
There is no remote daemon and no remote install. Every interaction is one
`ssh HOST sh -s` call whose stdin is a small POSIX-sh "agent" script (below)
prefixed with a header of quoted variables (operation, state path, identity,
acknowledged output offsets, ...). The agent inspects/updates per-invocation
state under the remote state path and answers on stdout using a tiny framed
protocol (a sentinel line, `key=value` lines, `end`, then raw stdout bytes,
then raw stderr bytes), so remote login banners and binary output are safe.

Remote state, one directory per identity (<state-path>/<sha256(argv)[:32]>/):

    cmdline       human-readable command
    run.sh        the runner: executes the command, records its exit status
    script        (script mode) the uploaded script
    umask         the umask to give the command (agent files are 0600)
    started       epoch seconds
    marker        process start-time marker (guards against PID reuse/reboot)
    pid           runner PID == process-group id (runner is a session leader)
    exit          "<exit-code> <epoch>", written atomically when the command ends
    stdout.log, stderr.log       append-only output
    stdout.off,  stderr.off      bytes already shown to (and acked by) a client

Output is at-least-once: a client acknowledges what it displayed on its next
call, so a dropped connection can duplicate a chunk but never lose one.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import re
import shlex
import signal
import subprocess
import sys
import time

# --------------------------------------------------------------------------
# Return codes. The remote command's own exit status is returned unchanged on
# normal completion, so these can unavoidably collide with a command's own
# codes; they are grouped at the top of the range, like ssh's own 255.
# --------------------------------------------------------------------------
EX_USAGE = 2           # bad command line (argparse convention)
EX_BAD_STATE = 250     # remote state corrupt/unreadable/vanished; status unknown
EX_LAUNCHED = 251      # --timeout 0: launched/reattached, deliberately not waited
EX_KILL_TIMEOUT = 252  # --kill: process still alive when --timeout expired
EX_TIMEOUT = 253       # normal mode: --timeout expired (or local interrupt)
EX_REMOTE = 254        # could not establish the remote run / remote-side error
EX_SSH = 255           # cannot reach host (SSH-level failure), as ssh itself

DEFAULT_POLL = 30.0
DEFAULT_KILL_POLL = 1.0
DEFAULT_TIMEOUT = -1.0
DEFAULT_KILL_TIMEOUT = 5.0
MAX_CHUNK = 1 << 20    # max bytes of each log returned per round trip

SSH_OPTS = ["-T", "-o", "ServerAliveInterval=15", "-o", "ServerAliveCountMax=3"]


class TeleError(Exception):
    def __init__(self, message: str, code: int):
        super().__init__(message)
        self.code = code


class Interrupted(Exception):
    """Local tele process was told to stop (SIGINT/SIGTERM/SIGHUP)."""


# --------------------------------------------------------------------------
# Remote side (POSIX sh)
# --------------------------------------------------------------------------

# Start-time marker for a PID; used by both the runner and the agent.
STARTTIME_SH = r"""starttime() {
  if [ -r "/proc/$1/stat" ]; then
    _b=$(cat /proc/sys/kernel/random/boot_id 2>/dev/null)
    _t=$(sed 's/^.*) //' "/proc/$1/stat" 2>/dev/null | cut -d' ' -f20)
    printf '%s:%s\n' "$_b" "$_t"
  else
    ps -o lstart= -p "$1" 2>/dev/null | sed 's/^ *//; s/  */ /g'
  fi
}"""

# The runner is the detached process. It ignores (well, defers) HUP/INT/TERM
# so that a signal sent to the whole process group only kills the command, and
# the runner can still record how the command ended.
RUNNER_TEMPLATE = r"""#!/bin/sh
# tele runner (generated by tele): runs the command and records its exit status.
D=$(cd "$(dirname "$0")" && pwd -P) || exit 1
trap : HUP INT TERM
@STARTTIME@
printf '%s\n' "$(starttime $$)" > "$D/marker.tmp" && mv "$D/marker.tmp" "$D/marker" || exit 1
printf '%s\n' "$$" > "$D/pid.tmp" && mv "$D/pid.tmp" "$D/pid" || exit 1
: >> "$D/stdout.log"
: >> "$D/stderr.log"
umask "$(cat "$D/umask" 2>/dev/null || echo 022)"
@RUN@ >> "$D/stdout.log" 2>> "$D/stderr.log" < /dev/null
rc=$?
umask 077
printf '%s %s\n' "$rc" "$(date +%s)" > "$D/exit.tmp" && mv "$D/exit.tmp" "$D/exit"
"""

AGENT_TEMPLATE = r"""
ORIG_UMASK=$(umask)
umask 077
MARK='@@TELE@@'
: "${ACK_OUT:=0}" "${ACK_ERR:=0}" "${MAXCHUNK:=1048576}" "${FORCE:=0}" "${DONE:=0}"
LAUNCHED=0; MORE=0
S=none; RC=; T_START=; T_END=
OUT_OFF=0; OUT_LEN=0; ERR_OFF=0; ERR_LEN=0

say() { printf '%s\n' "$*"; }

# emit STATE [key=value ...]: header, then the planned stdout/stderr bytes.
emit() {
  say "$MARK"
  say "state=$1"; shift
  for _kv in "$@"; do say "$_kv"; done
  say "outoff=$OUT_OFF"; say "outlen=$OUT_LEN"
  say "erroff=$ERR_OFF"; say "errlen=$ERR_LEN"
  say "more=$MORE"
  say "end"
  if [ "$OUT_LEN" -gt 0 ]; then
    tail -c +"$((OUT_OFF + 1))" "$D/stdout.log" | head -c "$OUT_LEN"
  fi
  if [ "$ERR_LEN" -gt 0 ]; then
    tail -c +"$((ERR_OFF + 1))" "$D/stderr.log" | head -c "$ERR_LEN"
  fi
  exit 0
}
respond() { OUT_LEN=0; ERR_LEN=0; emit "$@"; }
bail() { _s=$1; shift; respond "$_s" "msg=$(printf '%s' "$*" | tr '\n' ' ')"; }

@STARTTIME@

# is_live: 0 = live, 1 = not live, 2 = pid file unreadable
is_live() {
  [ -f "$D/pid" ] || return 1
  _pid=; read -r _pid < "$D/pid"
  case $_pid in ''|*[!0-9]*) return 2;; esac
  kill -0 "$_pid" 2>/dev/null || return 1
  _m=; [ -f "$D/marker" ] && read -r _m < "$D/marker"
  [ "$_m" = "$(starttime "$_pid")" ] || return 1
  # A zombie (killed, but not reaped by a PID 1 that ignores orphans, as in
  # some containers) still passes kill -0 and still matches the marker.
  _z=$(ps -o stat= -p "$_pid" 2>/dev/null)
  case $_z in Z*) return 1;; esac
  return 0
}

# load_state sets S to: none | running | ok | failed | died | corrupt
load_state() {
  S=none; RC=; T_START=; T_END=
  [ -d "$D" ] || return 0
  if [ ! -f "$D/run.sh" ] || [ ! -f "$D/cmdline" ]; then S=corrupt; return 0; fi
  [ -f "$D/started" ] && read -r T_START < "$D/started"
  if [ -f "$D/exit" ]; then
    read -r RC T_END < "$D/exit"
    case $RC in ''|*[!0-9]*) S=corrupt; return 0;; esac
    if [ "$RC" -eq 0 ]; then S=ok; else S=failed; fi
    return 0
  fi
  is_live; _l=$?
  case $_l in 0) S=running;; 2) S=corrupt;; *) S=died;; esac
  return 0
}

# plan STREAM ACK: apply the client's ack, then set _off/_len for the next
# chunk (bounded by MAXCHUNK; sets MORE=1 if more remains after it).
plan() {
  _f="$D/$1.log"; _o="$D/$1.off"; _off=0; _len=0
  [ -f "$_f" ] || return 0
  _size=$(wc -c < "$_f" | tr -d ' ')
  [ -f "$_o" ] && read -r _off < "$_o"
  case $_off in ''|*[!0-9]*) _off=0;; esac
  case $2 in ''|*[!0-9]*) ;; *) [ "$2" -gt "$_off" ] && _off=$2;; esac
  [ "$_off" -gt "$_size" ] && _off=$_size
  printf '%s\n' "$_off" > "$_o.tmp" && mv "$_o.tmp" "$_o"
  _len=$((_size - _off))
  if [ "$_len" -gt "$MAXCHUNK" ]; then _len=$MAXCHUNK; MORE=1; fi
  return 0
}

report() {
  MORE=0
  plan stdout "$ACK_OUT"; OUT_OFF=$_off; OUT_LEN=$_len
  plan stderr "$ACK_ERR"; ERR_OFF=$_off; ERR_LEN=$_len
  emit "$S" "rc=$RC" "started=$T_START" "finished=$T_END" "launched=$LAUNCHED" "dir=$D"
}

# detach CMD...: run CMD in its own session, fully detached from this ssh session.
detach() {
  if command -v setsid >/dev/null 2>&1; then
    setsid "$@" >/dev/null 2>"$D/launch.err" </dev/null &
  elif command -v perl >/dev/null 2>&1; then
    perl -e 'use POSIX (); POSIX::setsid(); exec @ARGV or exit 127' "$@" >/dev/null 2>"$D/launch.err" </dev/null &
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import os,sys; (os.setsid() if os.getpid()!=os.getpgid(0) else None); os.execvp(sys.argv[1], sys.argv[1:])' "$@" >/dev/null 2>"$D/launch.err" </dev/null &
  else
    nohup "$@" >/dev/null 2>"$D/launch.err" </dev/null &
  fi
}

launch() {
  rm -rf "$D"
  mkdir "$D" 2>/dev/null || bail remote_error "cannot create $D"
  { date +%s > "$D/started" \
    && printf '%s\n' "$CMDLINE" > "$D/cmdline" \
    && printf '%s\n' "$ORIG_UMASK" > "$D/umask" \
    && printf '%s\n' "$RUNNER" > "$D/run.sh"; } 2>/dev/null \
    || { rm -rf "$D"; bail remote_error "cannot write state under $D"; }
  if [ "$HAS_SCRIPT" = 1 ]; then
    printf '%s\n' "$SCRIPT" > "$D/script" || { rm -rf "$D"; bail remote_error "cannot write script"; }
  fi
  detach sh "$D/run.sh"
  _end=$(( $(date +%s) + 10 ))
  while [ ! -f "$D/pid" ] && [ ! -f "$D/exit" ] && [ "$(date +%s)" -lt "$_end" ]; do
    sleep 0.1 2>/dev/null || sleep 1
  done
  if [ ! -f "$D/pid" ] && [ ! -f "$D/exit" ]; then
    _err=$(head -c 500 "$D/launch.err" 2>/dev/null)
    rm -rf "$D"
    bail launch_failed "runner did not start${_err:+: $_err}"
  fi
  LAUNCHED=1
}

if [ "$OP" = invoke ]; then
  mkdir -p "$ROOT" 2>/dev/null || bail remote_error "cannot create state directory $ROOT"
  [ -O "$ROOT" ] || bail remote_error "state directory $ROOT is not owned by you"
fi
[ -d "$ROOT" ] && ROOT=$(cd "$ROOT" && pwd -P)
D="$ROOT/$ID"

case "$OP" in
  invoke)
    load_state
    case "$S" in
      none) launch ;;
      ok|corrupt) [ "$FORCE" = 1 ] && launch ;;
    esac
    [ "$LAUNCHED" = 1 ] && load_state
    report ;;

  poll)
    load_state
    report ;;

  # Record what the client displayed. With DONE=1 (the client has reported the
  # terminal outcome to its user) and everything drained, tidy up: delete logs
  # for a retained success, delete all state for a failure.
  ack)
    load_state
    [ "$S" = none ] && respond none
    plan stdout "$ACK_OUT"; _d1=$_len
    plan stderr "$ACK_ERR"; _d2=$_len
    if [ "$DONE" = 1 ] && [ "$_d1" -eq 0 ] && [ "$_d2" -eq 0 ]; then
      case "$S" in
        ok) rm -f "$D/stdout.log" "$D/stderr.log" "$D/stdout.off" "$D/stderr.off" ;;
        failed|died) rm -rf "$D" ;;
      esac
    fi
    respond "$S" ;;

  kill)
    load_state
    case "$S" in
      none) respond none ;;
      ok) respond ok ;;
      failed|died|corrupt) rm -rf "$D"; respond cleaned "was=$S" ;;
      running)
        read -r _pid < "$D/pid"
        # The runner is a session leader, so its pid is also its process-group
        # id and we signal the whole group (reaching the command's children).
        # If it is NOT a group leader (host has no setsid/perl/python3), only
        # the runner can be signalled. Note dash's kill rejects `--` after a
        # numeric signal, hence the two forms.
        _pg=$(ps -o pgid= -p "$_pid" 2>/dev/null | tr -d ' ')
        _sent=0
        if [ -z "$_pg" ] || [ "$_pg" = "$_pid" ]; then
          case $SIGOPT in
            -s*) kill $SIGOPT -- "-$_pid" 2>/dev/null && _sent=1 ;;
            *)   kill $SIGOPT "-$_pid" 2>/dev/null && _sent=1 ;;
          esac
        fi
        if [ "$_sent" = 0 ] && { [ -z "$_pg" ] || [ "$_pg" != "$_pid" ]; }; then
          kill $SIGOPT "$_pid" 2>/dev/null && _sent=1
        fi
        if [ "$_sent" = 1 ]; then
          respond running signaled=1
        else
          bail remote_error "could not send signal ($SIGOPT) to process group $_pid"
        fi ;;
    esac ;;

  killpoll)
    load_state
    case "$S" in
      running) respond running ;;
      none) respond none ;;
      *) rm -rf "$D"; respond gone "was=$S" ;;
    esac ;;

  *) bail remote_error "unknown operation: $OP" ;;
esac
"""

AGENT = AGENT_TEMPLATE.replace("@STARTTIME@", STARTTIME_SH)


# --------------------------------------------------------------------------
# Local helpers
# --------------------------------------------------------------------------
def eprint(*a):
    print(*a, file=sys.stderr, flush=True)


def note(msg: str):
    eprint(f"tele: {msg}")


def q(s: str) -> str:
    return shlex.quote(s)


def fmt_ts(epoch: str) -> str:
    try:
        return datetime.datetime.fromtimestamp(int(epoch)).astimezone().isoformat(timespec="seconds")
    except (ValueError, OverflowError, OSError):
        return "unknown time"


def remote_path_expr(path: str | None) -> str:
    """Shell expression (evaluated on the remote) for the state root."""
    if path is None:
        return '"${TMPDIR:-/tmp}/${USER:-$(id -un)}/tele"'
    if path == "~":
        return '"$HOME"'
    if path.startswith("~/"):
        return '"$HOME"/' + q(path[2:])
    return q(path)


def identity(argv: list[str]) -> str:
    """Identity = the command tokens exactly as tele received them."""
    blob = json.dumps(argv, separators=(",", ":")).encode()
    return hashlib.sha256(blob).hexdigest()[:32]


# --------------------------------------------------------------------------
# Signals
# --------------------------------------------------------------------------
KNOWN_SIGNALS = {s.name[3:] for s in signal.Signals}
_RT = re.compile(r"RT(MIN|MAX)([+-]\d+)?")


def _sig_name(tok: str) -> str:
    return tok[3:] if tok.startswith("SIG") else tok


def signal_option(spec: str) -> str | None:
    """Translate a kill(1)-style SIGNAL into remote `kill` options."""
    spec = spec.strip()
    if spec.isdigit():
        return f"-{int(spec)}"
    n = _sig_name(spec.upper())
    if n in KNOWN_SIGNALS or _RT.fullmatch(n):
        return f"-s {n}"
    return None


# --------------------------------------------------------------------------
# Command line
# --------------------------------------------------------------------------
class Spec:
    """What to run: mode is 'shell' | 'script' | 'exec'."""

    def __init__(self, mode: str, argv: list[str], script: str | None = None):
        self.mode, self.argv, self.script = mode, argv, script
        self.id = identity(argv)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="tele",
        allow_abbrev=False,
        usage=(
            "tele [options] ssh_host -- command\n"
            "       tele [options] ssh_host -- path\n"
            "       tele [options] ssh_host -- command [cmd_options] [cmd_args]\n"
            "       tele [options] --exec ssh_host -- command\n"
            "       tele --kill [--signal SIGNAL] [options] ssh_host -- command [cmd_options] [cmd_args]"
        ),
        description="Run a command on a remote host, idempotently and immune to hangups.",
        epilog="`--` separates tele's options and ssh_host from the remote command.",
    )
    p.add_argument("ssh_host", nargs="?", help="user@host, ssh://user@host:port, or an ssh_config Host")
    p.add_argument("--exec", action="store_true", help="run command directly, without a remote shell")
    p.add_argument("--poll", type=float, metavar="SECONDS",
                   help=f"poll interval (default {DEFAULT_POLL:g}; {DEFAULT_KILL_POLL:g} with --kill)")
    p.add_argument("--shell", metavar="SHELL", help="remote shell (default: remote login shell)")
    p.add_argument("--timeout", type=float, metavar="SECONDS",
                   help=f"max time to block: <0 forever, 0 don't wait, >0 seconds "
                        f"(default {DEFAULT_TIMEOUT:g}; {DEFAULT_KILL_TIMEOUT:g} with --kill)")
    p.add_argument("--force", action="store_true", help="re-run even if a previous run succeeded")
    p.add_argument("--state-path", metavar="PATH", help="remote state directory (default $TMPDIR/$USER/tele)")
    p.add_argument("--kill", action="store_true",
                   help="ensure no matching invocation is running, and clean up")
    p.add_argument("--signal", metavar="SIGNAL", default="TERM",
                   help="signal to send with --kill, name or number (default TERM)")
    return p


def parse_args(argv: list[str]):
    parser = build_parser()
    if "--" not in argv:
        if "-h" in argv or "--help" in argv:
            parser.parse_args(["--help"])
        parser.error("missing `--` separating ssh_host from the command")
    i = argv.index("--")
    pre, post = argv[:i], argv[i + 1:]

    args = parser.parse_args(pre)
    killing = args.kill

    if not killing and args.signal != "TERM":
        parser.error("--signal is only valid with --kill")

    if args.ssh_host is None:
        parser.error("ssh_host is required")
    if not post or not post[0]:
        parser.error("no command given after `--`")

    if args.exec and args.shell:
        parser.error("--shell and --exec are mutually exclusive")
    if killing and (args.force or args.exec or args.shell):
        parser.error("--force, --exec and --shell are not valid with --kill")

    if args.poll is None:
        args.poll = DEFAULT_KILL_POLL if killing else DEFAULT_POLL
    if args.timeout is None:
        args.timeout = DEFAULT_KILL_TIMEOUT if killing else DEFAULT_TIMEOUT
    if args.poll <= 0:
        parser.error("--poll must be > 0")

    args.sigopt = None
    if killing:
        args.sigopt = signal_option(args.signal)
        if args.sigopt is None:
            parser.error(f"unknown signal: {args.signal!r}")

    if args.exec or len(post) >= 2:
        spec = Spec("exec", post)
    elif os.path.isfile(post[0]):
        try:
            with open(post[0], "rb") as fh:
                raw = fh.read()
        except OSError as e:
            parser.error(f"cannot read script {post[0]!r}: {e.strerror}")
        if b"\0" in raw:
            parser.error(f"{post[0]!r} looks like a binary file, not a shell script")
        spec = Spec("script", post, raw.decode("utf-8", "surrogateescape"))
    else:
        spec = Spec("shell", post)
    return args, spec


def build_runner(args, spec: Spec) -> str:
    shell = " ".join(q(w) for w in shlex.split(args.shell)) if args.shell else '"${SHELL:-/bin/sh}"'
    if spec.mode == "exec":
        run = " ".join(q(a) for a in spec.argv)
    elif spec.mode == "script":
        run = f'{shell} "$D/script"'
    else:
        run = f"{shell} -c {q(spec.argv[0])}"
    return RUNNER_TEMPLATE.replace("@STARTTIME@", STARTTIME_SH).replace("@RUN@", run)


# --------------------------------------------------------------------------
# Talking to the remote agent
# --------------------------------------------------------------------------
class Response:
    def __init__(self, fields: dict[str, str], out: bytes, err: bytes):
        self.f, self.out, self.err = fields, out, err

    def s(self, key: str, default: str = "") -> str:
        return self.f.get(key, default)

    def i(self, key: str, default: int = 0) -> int:
        try:
            return int(self.f.get(key, default))
        except ValueError:
            return default

    state = property(lambda self: self.s("state"))
    msg = property(lambda self: self.s("msg", "unspecified remote error"))
    more = property(lambda self: self.i("more") == 1)
    launched = property(lambda self: self.i("launched") == 1)


MARK = b"@@TELE@@\n"


def parse_response(stdout: bytes) -> Response | None:
    start = stdout.find(MARK)
    if start < 0:
        return None
    pos = start + len(MARK)
    fields: dict[str, str] = {}
    while True:
        nl = stdout.find(b"\n", pos)
        if nl < 0:
            return None
        line = stdout[pos:nl].decode("utf-8", "replace")
        pos = nl + 1
        if line == "end":
            break
        k, _, v = line.partition("=")
        fields[k] = v
    outlen, errlen = int(fields.get("outlen", 0)), int(fields.get("errlen", 0))
    if len(stdout) - pos < outlen + errlen:
        return None  # truncated in flight
    out = stdout[pos:pos + outlen]
    err = stdout[pos + outlen:pos + outlen + errlen]
    return Response(fields, out, err)


class Remote:
    def __init__(self, host: str, state_path: str | None):
        self.host = host
        self.root_expr = remote_path_expr(state_path)
        base = shlex.split(os.environ.get("TELE_SSH", "ssh"))
        self.argv = base + SSH_OPTS + ["--", host, "sh", "-s"]

    def call(self, op: str, ident: str, **variables) -> Response:
        header = [f"OP={q(op)}", f"ROOT={self.root_expr}", f"ID={q(ident)}", f"MAXCHUNK={MAX_CHUNK}"]
        header += [f"{k.upper()}={q(str(v))}" for k, v in variables.items()]
        script = "\n".join(header) + "\n" + AGENT
        try:
            proc = subprocess.run(
                self.argv, input=script.encode("utf-8", "surrogateescape"),
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            )
        except FileNotFoundError as e:
            raise TeleError(f"cannot run {self.argv[0]!r}: {e.strerror}", EX_SSH)
        stderr = proc.stderr.decode("utf-8", "replace").strip()
        if proc.returncode == 255:
            raise TeleError(f"ssh to {self.host} failed: {stderr or 'no error output'}", EX_SSH)
        resp = parse_response(proc.stdout)
        if resp is None:
            detail = stderr or proc.stdout[:200].decode("utf-8", "replace").strip() or "no output"
            raise TeleError(f"unexpected reply from {self.host} (exit {proc.returncode}): {detail}", EX_REMOTE)
        if resp.state in ("remote_error", "launch_failed", "error"):
            raise TeleError(resp.msg, EX_REMOTE)
        return resp


# --------------------------------------------------------------------------
# Normal (launch / reattach) mode
# --------------------------------------------------------------------------
class Session:
    def __init__(self, remote: Remote, spec: Spec):
        self.remote, self.spec = remote, spec
        self.shown_out = 0
        self.shown_err = 0

    def call(self, op: str, **kw) -> Response:
        return self.remote.call(op, self.spec.id, ack_out=self.shown_out, ack_err=self.shown_err, **kw)

    def display(self, r: Response):
        try:
            if r.out:
                sys.stdout.buffer.write(r.out)
                sys.stdout.buffer.flush()
            if r.err:
                sys.stderr.buffer.write(r.err)
                sys.stderr.buffer.flush()
        except BrokenPipeError:
            raise Interrupted("output closed")
        self.shown_out = max(self.shown_out, r.i("outoff") + len(r.out))
        self.shown_err = max(self.shown_err, r.i("erroff") + len(r.err))

    def settle(self, done: bool = False):
        """Best-effort: tell the remote what we've shown (and, if done, tidy up)."""
        old = signal.signal(signal.SIGINT, signal.SIG_IGN)
        try:
            self.call("ack", done=int(done))
        except (TeleError, Interrupted):
            pass
        finally:
            signal.signal(signal.SIGINT, old)


def run_command(args, spec: Spec, remote: Remote) -> int:
    s = Session(remote, spec)
    timeout, poll, host = args.timeout, args.poll, args.ssh_host
    deadline = None if timeout < 0 else time.time() + timeout

    try:
        resp = s.call(
            "invoke", force=int(args.force), cmdline=shlex.join(spec.argv),
            runner=build_runner(args, spec), has_script=int(spec.mode == "script"),
            script=spec.script or "",
        )
        retained = not resp.launched   # first reply describes pre-existing state
        first = True
        while True:
            s.display(resp)
            st = resp.state

            if st == "none":
                raise TeleError(
                    "remote state disappeared while attached (cleaned up by another client?); "
                    "exit status unknown", EX_BAD_STATE)
            if st == "corrupt":
                raise TeleError(
                    f"remote state at {resp.s('dir')} is corrupt or unreadable; "
                    "use --force or --kill to discard it", EX_BAD_STATE)
            if resp.more:                       # backlog: drain before anything else
                resp, first = s.call("poll"), False
                continue

            if st == "running":
                if first and retained:
                    note(f"reattached to running command on {host}")
                first = False
                now = time.time()
                if timeout == 0:
                    s.settle()
                    note(f"command running on {host}; not waiting (--timeout 0)")
                    return EX_LAUNCHED
                if deadline is not None and now >= deadline:
                    s.settle()
                    note(f"timed out after {timeout:g}s; command still running on {host} "
                         "(re-run the same tele command to reattach)")
                    return EX_TIMEOUT
                time.sleep(poll if deadline is None else max(0.0, min(poll, deadline - now)))
                resp = s.call("poll")
                continue

            # Terminal: ok / failed / died. Tidy up remotely, then report locally.
            try:
                s.call("ack", done=1)
            except TeleError as e:
                note(f"warning: could not tidy remote state: {e}")
            rc = resp.i("rc")
            if st == "ok":
                if first and retained:
                    took = ""
                    if resp.s("started").isdigit() and resp.s("finished").isdigit():
                        took = f", took {int(resp.s('finished')) - int(resp.s('started'))}s"
                    note(f"already completed successfully on {host} at {fmt_ts(resp.s('finished'))} "
                         f"(exit 0{took}); not re-running. Use --force to run it again.")
                return 0
            if st == "failed":
                if first and retained:
                    note(f"previous run failed on {host} (exit {rc}); reported stored output and "
                         "cleared remote state. Re-run to retry.")
                return rc
            note(f"command on {host} ended without recording an exit status "
                 "(killed, or host rebooted?); remote state cleared. Re-run to retry.")
            return EX_BAD_STATE
    except Interrupted:
        s.settle()
        raise


# --------------------------------------------------------------------------
# Kill mode
# --------------------------------------------------------------------------
def run_kill(args, spec: Spec, remote: Remote) -> int:
    timeout, poll = args.timeout, args.poll
    r = remote.call("kill", spec.id, sigopt=args.sigopt)
    if r.state in ("none", "ok", "cleaned"):
        return 0
    deadline = None if timeout < 0 else time.time() + timeout
    while True:                                    # state == running, signal sent
        r = remote.call("killpoll", spec.id)
        if r.state in ("gone", "none"):
            return 0
        now = time.time()
        if deadline is not None and now >= deadline:
            note(f"{args.signal} sent, but the command is still running on {args.ssh_host} "
                 f"after {timeout:g}s; no cleanup done (retry, e.g. with a stronger signal)")
            return EX_KILL_TIMEOUT
        time.sleep(poll if deadline is None else max(0.0, min(poll, deadline - now)))


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------
def _on_signal(signum, _frame):
    raise Interrupted(signal.Signals(signum).name)


def main(argv: list[str] | None = None) -> int:
    args, spec = parse_args(sys.argv[1:] if argv is None else argv)
    remote = Remote(args.ssh_host, args.state_path)
    killing = args.kill

    for name in ("SIGINT", "SIGTERM", "SIGHUP"):
        if hasattr(signal, name):
            signal.signal(getattr(signal, name), _on_signal)
    try:
        return run_kill(args, spec, remote) if killing else run_command(args, spec, remote)
    except TeleError as e:
        note(str(e))
        return e.code
    except Interrupted:
        if killing:
            note("interrupted; the kill signal may already have been delivered")
            return EX_KILL_TIMEOUT
        note("interrupted; the remote command is unaffected (re-run the same tele command to reattach)")
        return EX_TIMEOUT


if __name__ == "__main__":
    sys.exit(main())